GoogleCloudPlatform/pubsec-declarative-toolkit

- solutions/guardrails/configs/org-policies/org-policies.yaml
Fixed misconfigured org policies. Turned settings from allow all `true` to allow all `false`.
This will impact the `resourcelocation` and `vmexternalipaccess` policies. Default will now be to deny all for non-compliant resources.
> Changed external IP and location resources to allowAll: false

- cli/docs/solution.md
- cli/internal/cmdsolutiondeploy/cmdsolutiondeploy.go
- cli/pkg/api/solution/v1/types.go
Updated solution.yaml spec to include the ability to enable Google Cloud api services in projects (usually in a different project than the target for the solution) and dependencies that must be created first before the solution can be deployed.
Example of services would something like sqladmin.googleapis.com that needs to be enabled on the KCC host project in order for it be able to setup Cloud SQL on the target / tenant project.
The dependencies check uses the Google Cloud Asset Inventory gcloud command, thanks @cartyc for the idea!
> Added services to enable, depencies to check in solution spec

- solutions/landing-zone/.krmignore
Added `.krmignore` file to landing zone solution to ignore the cicd-examples directory. KRM Ignore files work similarly to `.gitignore` files and will tell `kpt` to ignore files or directories included in it.
This fixes an issue where `kpt` tries to run `render` on the yaml in the CICD examples directory but fails due to the lack of a `apiVersion` key. By ommiting the directory the folder is ommited and `kpt` will ignore it during the `render` phase.
> added krmignore file and added cicd-examples to it

- solutions/landing-zone/environments/common/policies/org-policies.yaml
Removed unsupported value for loadbalancers and set externalip to deny all true instead of allow all false.
Deployed lz into a new cluster and both policies (`restrict-vm-external-access`, and `restrict-loadbalancer-creation-types`) failed to provision. This update fixes the issue and policies should now come up with no issues.
> Update allowed Load Balancer and external VM IP Policies

- .github/workflows/landing-zone-validation.yaml
This PR will add a github action to test and validate the Landing Zone Solution.
The Action will run two steps, the first will run `kpt fn render` to test the render process and populate the LZ with the default values. The second step will run [nomos vet](https://cloud.google.com/anthos-config-management/docs/how-to/nomos-command) on the newly render landing zone to check for any errors in the solution.
> added gh action to validate landing zone solution

- solutions/landing-zone/README.md
see https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/111#issuecomment-1242747264
before
```
michael@cloudshell:~/github/GoogleCloudPlatform/20220909-103/landing-zone (lz-20220910-oldev)$ cd landing-zone/
-bash: cd: landing-zone/: No such file or directory
```
after
```
michael@cloudshell:~/github/GoogleCloudPlatform/20220909-103 (lz-20220910-oldev)$ cd landing-zone/
michael@cloudshell:~/github/GoogleCloudPlatform/20220909-103/landing-zone (lz-20220910-oldev)$ kpt fn render
Package "landing-zone/environments/common/guardrails-policies":
Successfully executed 9 function(s) in 5 package(s).
michael@cloudshell:~/github/GoogleCloudPlatform/20220909-103/landing-zone (lz-20220910-oldev)$ cd ..
michael@cloudshell:~/github/GoogleCloudPlatform/20220909-103 …
```
> #111 - fix kpt steps for in/out lz dir

- solutions/landing-zone/environments/common/guardrails-policies/05-data-location/constraint.yaml
This PR fixes a typo in the constraint.yaml file name in the datalocation guardrail.
File name was constaint.yaml instead of constraint.yaml.
> fixed typo in file name

- solutions/landing-zone/README.md
test results
```
admin_@cloudshell:~/wse_github/20220829 (pubsec-declarative-toolkit-arg)$ export REGION=northamerica-northeast1
export PROJECT_ID=$(gcloud config list --format 'value(core.project)')
export ORG_ID=$(gcloud projects get-ancestors $PROJECT_ID --format='get(id)' | tail -1)
export EMAIL=$(gcloud config list --format json|jq .core.account | sed 's/"//g')
gcloud organizations add-iam-policy-binding "${ORG_ID}" --member "user:${EMAIL}" --role roles/logging.admin
gcloud alpha logging settings update --organization=$ORG_ID --storage-location=$REGION
Updated IAM policy for organization [226082700214].
...
admin_@cloudshell:~/wse_github/20220829 (pubsec-declarative-toolkit-arg)$ gcloud organizations get-iam-policy $ORG_ID --filter="bindings.members:$EMAIL" …
```
> #104 - align guardrails email gen to lz

- cli/internal/cmdcreate/cmdcreate.go
Update the locations that area avail to create Config Controller cluster. 
https://cloud.google.com/anthos-config-management/docs/how-to/config-controller-setup
> Updated CC avail regions

- solutions/landing-zone/README.md
Updating documentation on LZ deployment. 
This PR is aimed at improving the documentation around deploying with `kpt` and GitOps options. I am hoping to make things clearer as to what the different options do and when to use them.
Leaving this as a draft to collect more input and to test the new instructions around using OCI.
> Update to LZ deployment Docs

- solutions/landing-zone/environments/common/audit/audit-bucket.yaml
Added missing namespace on audit bucket storage. This will fix the issue of the audit bucket being provisioned in the `default` namespace instead of the expected `config-control` namespace.
> added missing namespace

- solutions/landing-zone/environments/common/audit/audit-bucket.yaml
- solutions/landing-zone/environments/common/audit/log-bucket.yaml
This pr replaces the existing `IAMPolicy` which relied on the `kpt` `apply-time-mutation` annotation to inject the `LoggingLogSink` writer identity value with the newer `IAMPartialPolicy`. 
`IAMPartialPolicy` allows us to reference the `LoggingLogSink` object directly and apply the required permissions to the underlying writer Identity without needing to know what it is beforehand.
IAMPartialPolicy docs --> https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampartialpolicy#supported_resources
> replaced IAM Policy with IAMPartialPolicy

- .github/workflows/guardrails-validation.yaml
- solutions/guardrails/Kptfile
- solutions/guardrails/configs/log-sinks/bigquery-sink.yaml
- solutions/guardrails/configs/log-sinks/pubsub-sink.yaml
- solutions/guardrails/configs/log-sinks/storage-sink.yaml
- solutions/guardrails/configs/org-policies/org-policies.yaml
This PR updates the logginglogsink objects to use IAMPartialPolicy instead of relying on the `apply-time-mutation` feature.
Additionally adds a github action for validation of the guardrails solution and adds folder creation to the `kptfile` pipeline.
> Guardrails logsink iam

- .github/workflows/guardrails-validation.yaml
Updated path for guardrails solution in Nomos command.
CI test now works, see https://github.com/cartyc/pubsec-declarative-toolkit/actions/runs/3244668299 for a successful run.
> updated test path

- solutions/landing-zone-namespaced/landing-zone/Kptfile
- solutions/landing-zone-namespaced/landing-zone/setters.yaml
merging latest updates to solutions/landing-zone
fix mutator sequence to ensure the enable-gcp-services remains last to avoid the bug where single quote gets replaced by double quote or no quotes
> resolve #193 : fixed mutators by keeping enable-gcp-services last

- .github/workflows/guardrails-validation.yaml
- .github/workflows/landing-zone-validation.yaml
Updated the nomos container to use `v1.13.1` instead of `stable`. The latest stable release does not include the `nomos` binary which has been causing the validation actions to fail.
Reverting to `v1.13.1` as the `nomos` binary is included in that release.
Will squash the merge as there are a few additional empty commits where I added a verified commit.
> fix: Nomos update

- services/private-sql/fn-setters.yaml
- services/private-sql/sql.yaml
- solutions/sandbox-gke/README.md
- solutions/sandbox-gke/artifact-registry/registry.yaml
- solutions/sandbox-gke/network/computerouter.yaml
- solutions/sandbox-gke/network/computerouternat.yaml
- solutions/sandbox-gke/network/subnetwork.yaml
- solutions/sandbox-gke/private-gke/gke/bigquerydataset.yaml
- solutions/sandbox-gke/private-gke/gke/containercluster.yaml
- solutions/sandbox-gke/setters.yaml
This is a small  PR that addresses the mislabeled regions  mentioned in #278 and sets any remaining regions set to use `us-central1` to be `northamerica-northeast1` as a default.
> fix: updated default regions for sandbox-gke and private-sql examples

- .release-please-manifest.json
- release-please-config.json
- solutions/logging/client-env/Kptfile
- solutions/logging/client-env/README.md
- solutions/logging/client-env/cloud-logging-bucket.yaml
- solutions/logging/client-env/folder-sink.yaml
- solutions/logging/client-env/project-iam.yaml
- solutions/logging/client-env/securitycontrols.md
- solutions/logging/client-env/setters.yaml
- solutions/logging/core-experimentation/CHANGELOG.md
- solutions/logging/core-experimentation/org-sink.yaml
This, along with the core-env logging package closes #337
- initial deployment of client-env logging package
- implementation is dependent on core-env logging package
> feat: logging client-env package

- README.md
Fixed url link to SSC docs, I had the url and text flipped in the markdown.
> docs:fixed typo

- solutions/client-project-setup/Kptfile
- solutions/client-project-setup/README.md
- solutions/client-project-setup/namespaces/project-id-tier3.yaml
- solutions/client-project-setup/namespaces/project-id-tier4.yaml
- solutions/client-project-setup/project-iam.yaml
- solutions/client-project-setup/project.yaml
- solutions/client-project-setup/root-sync-git/root-sync-git.yaml
- solutions/client-project-setup/services.yaml
- solutions/client-project-setup/setters.yaml
new package for issue #370
(additional PRs will be created for other packages and to update documentation)
**`solutions/client-project-setup`**
- includes / deprecates packages:
- none
- adds features:
- client tier3 and tier4 namespaces
- client tier3/4 root sync
- client shared vpc service project
- depends on:
- solutions/client-landing-zone
> feat: add client-project-setup package

- solutions/experimentation/client-landing-zone/Kptfile
- solutions/experimentation/client-landing-zone/README.md
- solutions/experimentation/client-landing-zone/client-folder/applications/folder.yaml
- solutions/experimentation/client-landing-zone/client-folder/folder-iam.yaml
- solutions/experimentation/client-landing-zone/client-folder/folder-sink.yaml
- solutions/experimentation/client-landing-zone/client-folder/folder.yaml
- solutions/experimentation/client-landing-zone/logging-project/cloud-logging-bucket.yaml
- solutions/experimentation/client-landing-zone/logging-project/project-iam.yaml
- solutions/experimentation/client-landing-zone/logging-project/securitycontrols.md
- solutions/experimentation/client-landing-zone/setters.yaml
new package for issue #370
(additional PRs will be created for other packages and to update documentation)
**`solutions/experimentation/client-landing-zone`**
- includes / deprecates packages:
- solutions/hierarchy/client-experimentation
- solutions/logging/client-experimentation
- depends on:
- solutions/experimentation/core-landing-zone
> feat: add experimentation client-landing-zone package

- solutions/experimentation/admin-folder/CHANGELOG.md
- solutions/experimentation/admin-folder/Kptfile
- solutions/experimentation/admin-folder/README.md
- solutions/experimentation/admin-folder/folder-iam.yaml
- solutions/experimentation/admin-folder/folder.yaml
- solutions/experimentation/admin-folder/setters.yaml
new package for issue #370
(additional PRs will be created for other packages and to update documentation)
**`solutions/experimentation/admin-folder`**
- includes / deprecates packages:
- solutions/hierarchy/admin-experimentation
- depends on:
- solutions/experimentation/core-landing-zone
> feat: add experimentation admin folder package

- examples/landing-zone-v2/Kptfile
- examples/landing-zone-v2/README.md
- examples/landing-zone-v2/setters.yaml
- examples/landing-zone-v2/tier3/cloud-armor/README.md
- examples/landing-zone-v2/tier3/cloud-armor/security-policy.yaml
- examples/landing-zone-v2/tier3/external-load-balancer/README.md
- examples/landing-zone-v2/tier3/external-load-balancer/address.yaml
- examples/landing-zone-v2/tier3/external-load-balancer/backend-service.yaml
- examples/landing-zone-v2/tier3/external-load-balancer/elb.yaml
- examples/landing-zone-v2/tier3/external-load-balancer/firewall.yaml
- examples/landing-zone-v2/tier3/external-load-balancer/forwarding-rule.yaml
- examples/landing-zone-v2/tier3/external-load-balancer/health-check.yaml
- examples/landing-zone-v2/tier3/external-load-balancer/target-http-proxy.yaml
- examples/landing-zone-v2/tier3/firewall-policy-rules/README.md
- examples/landing-zone-v2/tier3/firewall-policy-rules/allow-egress-fqdns.yaml
- examples/landing-zone-v2/tier3/remote-access-to-gce/README.md
- examples/landing-zone-v2/tier3/remote-access-to-gce/firewall-iap.yaml
- examples/landing-zone-v2/tier4/managed-instance-group/README.md
- examples/landing-zone-v2/tier4/managed-instance-group/instance-group-manager.yaml
- examples/landing-zone-v2/tier4/managed-instance-group/instance-template.yaml
- examples/landing-zone-v2/tier4/managed-instance-group/service-account.yaml
- solutions/client-landing-zone/README.md
- solutions/client-landing-zone/client-folder/standard/org-policies/exceptions/compute-restrict-load-balancer-creation-for-types.yaml
- solutions/client-project-setup/README.md
- solutions/client-project-setup/namespaces/project-id-tier4.yaml
- solutions/client-project-setup/setters.yaml
- solutions/client-setup/README.md
- solutions/client-setup/namespaces/client-name-hierarchy.yaml
closes #391 
cleanup permissions, org policies and provide examples to deploy cloud armor policies
`client-setup`
- add client name hierarchy viewer to policies
`client-landing-zone`
- add org policy exception for lb types on the standard folder
`client-project-setup`
- tier4-sa: remove editor role (too much overlap with security roles) and compute instance admin
- tier4-sa: move network user permissions from host project to subnets
`examples`
- add tier3/cloud-armor
- add tier3/external-load-balancer
- add tier3/remote-access-to-gce
- add tier4/managed-instance-group
> feat: add cloud armor resources

- solutions/client-setup/README.md
- solutions/client-setup/setters.yaml
Addressing missing `dns-project-id` setter. 
This is required to allow the following resource to be created [client-name-networking.yaml](https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/client-setup/namespaces/client-name-networking.yaml) 
```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
...
```
> fix: adding missing dns project id setter

- examples/landing-zone-v2/tier3/dns/address.yaml
- examples/landing-zone-v2/tier3/dns/dns.yaml
**Fixes**
- adjusting compute address name
- fixing dns spec name, missing double quotes
- fixing rrdatasRefs name
- removing namespace reference to tier 4. We had decided to pair DNS A record and its compute address inside `tier3`
> fix: fixing DNS tier3 example

- solutions/client-project-setup/project.yaml
This PR addresses the issue described in #422 by removing the `depends-on` annotation from the project object in `project.yaml`.
This change helps ensure that this package is not trying to reach across `resourceGroups` either in `kpt` or `config-sync`. In `kpt` this would be the resources that are captured in the `kpt live init` command or in `config-sync` the scope of the `root` or `repo` sync objects.
> fix: remove external depends-on annotation

- README.md
ongoing #296 day0 instructions
make the instructions clearer on the 2 step quickstart - to avoid client confusion
- install the kcc cluster
- install a default landing-zone-v2 - composed of the dual pkg - core-landing-zone and experimentation/core-landing-zone
verified all link changes
> #296 -  day0 install readme must include 2 core-landing-zone pkg instructions link

- docs/landing-zone-v2/README.md
merge this one after the merge and rebase of 
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/pull/458
An inadvertent result of a sequence of PRs where one merged that moved files that were previously in another spot when the previous linked to them ok.
fix
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/docs/landing-zone-v2#2-create-your-landing-zone
link
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/landing-zone-v2/setters.yaml
to
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/core-landing-zone/setters.yaml
dont need to reference where it actually is - as it is now deprecated in
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/main/solutions/l …
> #475 - fix legacy move of lz v2 incoming link

- solutions/gke/configconnector/gke-setup/Kptfile
- solutions/gke/configconnector/gke-setup/README.md
- solutions/gke/configconnector/gke-setup/gkehub-feature-acm.yaml
- solutions/gke/configconnector/gke-setup/host-project/project-iam.yaml
- solutions/gke/configconnector/gke-setup/logging-monitoring/alerts.yaml
- solutions/gke/configconnector/gke-setup/logging-monitoring/notificationchannel.yaml
- solutions/gke/configconnector/gke-setup/logging-monitoring/pubsub.yaml
- solutions/gke/configconnector/gke-setup/project-iam.yaml
- solutions/gke/configconnector/gke-setup/securitycontrols.md
- solutions/gke/configconnector/gke-setup/services.yaml
- solutions/gke/configconnector/gke-setup/setters.yaml
Landing zone v2 subpackage.
Depends on package `client-project-setup`.
Deploy this package once per service project.
Package to prepare a service project for GKE clusters. 
- several APIs are enabled
- enables anthos config management
- defines a monitoring foundation
- grant permissions on the host project to api service accounts
provides a portion of the solution to #479
> feat: gke-setup package

- solutions/gke/configconnector/gke-cluster-autopilot/Kptfile
- solutions/gke/configconnector/gke-cluster-autopilot/README.md
- solutions/gke/configconnector/gke-cluster-autopilot/application-infrastructure-folder/firewall.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/gke.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/gkehub-featuremembership-acm.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/gkehub-membership.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/host-project/firewall.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/host-project/subnet.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/kms.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/securitycontrols.md
- solutions/gke/configconnector/gke-cluster-autopilot/service-account.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/setters.yaml
Landing zone v2 subpackage.
Depends on package `gke-setup`.
Requires project-id-tier3 namespace.
Deploy this package once per GKE cluster.
A GKE Autopilot Cluster running in a service project. This package also deploys a dedicated subnet inside the host project.
- firewall policy rules to allow traffic toward github, azdo and docker registry
- subnet in host project
- gke cluster
- anthos fleet
- anthos config management
- kms key for etcd encryption
- service account with least privilege roles
This package contributes to the solution for #479
> feat: gke-cluster-autopilot package

- solutions/gke/kubernetes/cluster-defaults/Kptfile
- solutions/gke/kubernetes/cluster-defaults/README.md
- solutions/gke/kubernetes/cluster-defaults/admin-namespaces/gateway.yaml
- solutions/gke/kubernetes/cluster-defaults/gateway/Kptfile
- solutions/gke/kubernetes/cluster-defaults/gateway/backendpolicy/Kptfile
- solutions/gke/kubernetes/cluster-defaults/gateway/backendpolicy/backendpolicy.yaml
- solutions/gke/kubernetes/cluster-defaults/gateway/backendpolicy/setters.yaml
- solutions/gke/kubernetes/cluster-defaults/gateway/gateway-global.yaml
- solutions/gke/kubernetes/cluster-defaults/gateway/gateway-regional.yaml
- solutions/gke/kubernetes/cluster-defaults/gateway/gcpgatewaypolicy.yaml
- solutions/gke/kubernetes/cluster-defaults/gateway/setters.yaml
- solutions/gke/kubernetes/cluster-defaults/securitycontrols.md
This package deploys to a GKE cluster.
It should be deployed once per cluster.
This package deploys default resources that have to exist on all clusters.
---
Resources list:
- Gateway Controller
- gateway namespace
- Gateway using an external global load balancer and a SSL certificate
- Attaches an SSL Policy
- Attaches a Cloud Armor and logging policy
contributes to #479
> feat: kubernetes default package

- solutions/gke/configconnector/gke-defaults/Kptfile
- solutions/gke/configconnector/gke-defaults/README.md
- solutions/gke/configconnector/gke-defaults/gateway-setup/Kptfile
- solutions/gke/configconnector/gke-defaults/gateway-setup/README.md
- solutions/gke/configconnector/gke-defaults/gateway-setup/dns/Kptfile
- solutions/gke/configconnector/gke-defaults/gateway-setup/dns/README.md
- solutions/gke/configconnector/gke-defaults/gateway-setup/dns/dns.yaml
- solutions/gke/configconnector/gke-defaults/gateway-setup/dns/setters.yaml
- solutions/gke/configconnector/gke-defaults/gateway-setup/ip.yaml
- solutions/gke/configconnector/gke-defaults/gateway-setup/setters.yaml
- solutions/gke/configconnector/gke-defaults/gateway-setup/ssl-certificate/Kptfile
- solutions/gke/configconnector/gke-defaults/gateway-setup/ssl-certificate/README.md
- solutions/gke/configconnector/gke-defaults/gateway-setup/ssl-certificate/setters.yaml
- solutions/gke/configconnector/gke-defaults/gateway-setup/ssl-certificate/ssl.yaml
- solutions/gke/configconnector/gke-defaults/project-iam.yaml
- solutions/gke/configconnector/gke-defaults/securitycontrols.md
- solutions/gke/configconnector/gke-defaults/setters.yaml
Landing zone v2 subpackage.
Depends on package `gke-setup`.
Requires project-id-tier3 namespace.
Deploy this package once per service project.
A package to deploy common GKE resources. 
- include roles granted to a user or group for visualizing GKE.
- ip reservation for an external global load balancers
- ssl certificate (requires the alpha CRD for now)
- dns record
This package is part of the solution for #479
> feat: gke-defaults package

- solutions/gke/kubernetes/namespace-defaults/Kptfile
- solutions/gke/kubernetes/namespace-defaults/README.md
- solutions/gke/kubernetes/namespace-defaults/cd/cd-rolebinding.yaml
- solutions/gke/kubernetes/namespace-defaults/cd/gitops-config-sync.yaml
- solutions/gke/kubernetes/namespace-defaults/limitrange.yaml
- solutions/gke/kubernetes/namespace-defaults/namespace.yaml
- solutions/gke/kubernetes/namespace-defaults/networkpolicy.yaml
- solutions/gke/kubernetes/namespace-defaults/resourcequota.yaml
- solutions/gke/kubernetes/namespace-defaults/rolebinding-httproute-admin.yaml
- solutions/gke/kubernetes/namespace-defaults/rolebinding-team-view.yaml
- solutions/gke/kubernetes/namespace-defaults/securitycontrols.md
- solutions/gke/kubernetes/namespace-defaults/setters.yaml
Landing zone v2 subpackage.
Depends on package `cluster-defaults`.
This package deploys to a GKE cluster.
It should be deployed once per workload namespace.
This package deploys a workload namespace and it's associated configuration.
---
Resources list:
- namespace
- resourcequota
- limitrange
- networkpolicies
- rolebinding for an application team
- a choice of Continuous Delivery(CD) solution which offer ConfigSync (Default) or ServiceAccount permission for external tools.
contributes to #479
> feat: kubernetes namespace defaults package

- solutions/gke/kubernetes/namespace-defaults/cd/gitops-config-sync.yaml
closes #496 
The Anthos Config Management feature is enabled on the cluster. There is a known issue with the root-sync resource when deployed to an autopilot cluster.
The reconciler container keeps crashing with an out-of-memory error message because it hits the memory limit.
To fix this, you need the override section in the `rootsync` resources.
> fix: root-sync adding override

- solutions/client-landing-zone/client-folder/standard/org-policies/exceptions/compute-restrict-load-balancer-creation-for-types.yaml
This PR aims to address issue #503 by adding the client name to the org policy to give it a unique value and prevent conflicts with other clients policies.
> fix: Resolve conflicting Client LZ Loadbalancer Policy

- .release-please-manifest.json
- release-please-config.json
- solutions/client-setup/README.md
- solutions/client-setup/namespaces/client-name-admin.yaml
- solutions/client-setup/namespaces/client-name-networking.yaml
- solutions/client-setup/setters.yaml
- solutions/gke/configconnector/gke-admin-proxy/Kptfile
- solutions/gke/configconnector/gke-admin-proxy/README.md
- solutions/gke/configconnector/gke-admin-proxy/instance-resources/Kptfile
- solutions/gke/configconnector/gke-admin-proxy/instance-resources/README.md
- solutions/gke/configconnector/gke-admin-proxy/instance-resources/address.yaml
- solutions/gke/configconnector/gke-admin-proxy/instance-resources/firewall-iap.yaml
- solutions/gke/configconnector/gke-admin-proxy/instance-resources/iam.yaml
- solutions/gke/configconnector/gke-admin-proxy/instance-resources/instance.yaml
- solutions/gke/configconnector/gke-admin-proxy/instance-resources/setters.yaml
- solutions/gke/configconnector/gke-admin-proxy/project-iam.yaml
- solutions/gke/configconnector/gke-admin-proxy/securitycontrols.md
- solutions/gke/configconnector/gke-admin-proxy/setters.yaml
supports #479
- `/solutions/client-setup`
- add new client admin namespace for adhoc administrative tasks.
- `/solutions/gke/configconnector/gke-admin-proxy`
- new package to assist in the administration of a private GKE cluster
> feat: add client admin ns and gke admin proxy

- solutions/gke/configconnector/gke-setup/host-project/project-iam.yaml
using proper role id for gke firewall admin
closes #509
> fix: gke-setup - using proper role id for gke firewall admin

- solutions/gke/kubernetes/namespace-defaults/README.md
- solutions/gke/kubernetes/namespace-defaults/namespace-sa.yaml
- solutions/gke/kubernetes/namespace-defaults/networkpolicy.yaml
- solutions/gke/kubernetes/namespace-defaults/setters.yaml
updating kubernetes `namespace-defaults` package
- Creates Kuberenetes Service Account to be used by applications deployed in the namespace. Kubernetes Service Account is annotated with the Google Service Account to which it is bound using workload identity.
- Network policy to allow access to NodeLocal DNSCache on ip 169.254.20.10 and port 53
- Network policy to allow egress for GCP API
- update README.md
contributes to #479
> feat: namespace-defaults - adding sa for wi and update network policy

- solutions/gke/kubernetes/cluster-defaults/network-logging.yaml
updating kubernetes `cluster-defaults` package
Enables logging for traffic allowed / blocked by Network Policies
More info: https://cloud.google.com/kubernetes-engine/docs/how-to/network-policy-logging
> feat: cluster-defaults - adding logging to network policies

- solutions/vertexai/ai-experimentation/Kptfile
- solutions/vertexai/ai-experimentation/README.md
- solutions/vertexai/ai-experimentation/policies.yaml
- solutions/vertexai/ai-experimentation/project-iam.yaml
- solutions/vertexai/ai-experimentation/project.yaml
- solutions/vertexai/ai-experimentation/services.yaml
- solutions/vertexai/ai-experimentation/setters.yaml
This package includes a project that is pre-configured with the required services to begin using vertex ai for experimentation with Google AI services.
Some services are not fully available in Canada and this project adds an organization policy exemption for the target project to facilitate the deployment. This package is not intended for use beyond profile 1 and the experimentation Landing Zone.
A future package will be added to demonstrate the creation of vertex ai components  using KRM.
> feat: Add AI Experimentation Solution

- examples/landing-zone-v2/configconnector/tier3/external-load-balancer/firewall.yaml
- examples/landing-zone-v2/configconnector/tier3/firewall-policy-rules/allow-egress-fqdns.yaml
- examples/landing-zone-v2/configconnector/tier3/remote-access-to-gce/firewall-iap.yaml
- solutions/client-landing-zone/client-folder/firewall-policy/rules/defaults.yaml
- solutions/client-landing-zone/client-folder/firewall-policy/rules/iap.yaml
- solutions/client-landing-zone/client-folder/firewall-policy/rules/lb-health-checks.yaml
- solutions/client-landing-zone/client-folder/standard/applications-infrastructure/firewall-policy/rules/defaults.yaml
- solutions/client-landing-zone/client-folder/standard/applications-infrastructure/firewall-policy/rules/iap.yaml
- solutions/client-landing-zone/client-folder/standard/applications-infrastructure/firewall-policy/rules/lb-health-checks.yaml
- solutions/client-landing-zone/client-folder/standard/applications-infrastructure/host-project/network/firewall.yaml
- solutions/client-landing-zone/client-folder/standard/applications-infrastructure/host-project/network/psc/google-apis/firewall.yaml
- solutions/gke/configconnector/gke-admin-proxy/instance-resources/firewall-iap.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/host-project/firewall.yaml
- solutions/project/hub-env/fortigate/firewall.yaml
- solutions/project/hub-env/fortigate/management-vm/firewall.yaml
- solutions/project/hub-env/samples/Egress-workload-to-common-services.md
- solutions/project/hub-env/samples/Ingress-internet-to workload.md
- solutions/project/spoke-unclass-env/network/psc/google-apis/firewall.yaml
closes #523 
enable logging on firewall rules that had it disabled
> fix: enable missing logging for fw rules

- docs/landing-zone-v2/README.md
Use the main release for all kpt packages until we fix the URL and the json parsing around URL="https://api.github.com/repos/GoogleCloudPlatform/pubsec-declarative-toolkit/releases"
These 3 script sections were tested in one of my organizations
Later I will look at the full fix for release extraction from the json release URL above - no time right now.
> #540 - adjust LZ README.md add json release URL for KPT instructions

- solutions/project/hub-env/project.yaml
- solutions/project/hub-env/setters.yaml
This PR removes the depends-on annotation from the hub project and adds the `management-project-id` variable to the setters file.
> Update to Fortinet Hub ENV Package

- solutions/project/hub-env/fortigate/management-vm/management-vm.yaml
… e2-standard and leave n2-standard to FG VMs
see testing in #625 and #446
essentially out of the box organizations will have a N2_CPUS quota of 8. Attempting to increase this quota does not always get approved even for 10 vCores
Temporary fix is use a slightly different machine type e2-standard-2 for just the management VM
VMs come up after this
```
Status:
Conditions:
Last Transition Time:  2023-10-27T21:07:26Z
Message:               The resource is up to date
Reason:                UpToDate
Status:                True
Type:                  Ready
Cpu Platform:            Intel Cascade Lake
Current Status:          RUNNING
Instance Id:             5974440820601886829
Label Fingerprint:       Z9VAAJ71T-w=
Metadata Fingerprint:    GXJWD0MkUvs=
Observed Generation:     7
Self Link: …
```
> #625 - 446 N2_CPUS quota of 8 requires fortigate management vm to use e2-standard and leave n2-standard to FG VMs

- solutions/client-landing-zone/client-folder/standard/applications-infrastructure/host-project/network/nat.yaml
Closes #637
Updating client-landing-zone package.
Enables logging for Cloud NAT
https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computerouternat
Spec added (ALL=Translation and errors):
```yaml
logConfig:
enable: true
filter: ALL
```
> feat: enable logging on cloud nat resources

- solutions/client-landing-zone/client-folder/standard/applications-infrastructure/host-project/services.yaml
Update services in client-landing-zone package to use `projectRef` instead of `project-id` annotation.
> fix: added projectref and removed project-id annotation

- solutions/gke/configconnector/gke-cluster-autopilot/Kptfile
- solutions/gke/configconnector/gke-cluster-autopilot/README.md
- solutions/gke/configconnector/gke-cluster-autopilot/gke.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/host-project/subnet.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/setters.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/starlark-update-containercluster.yaml
- changing default ip ranges for pods to use `172.16.0.0/23` by default instead of RFC5735
- changing default ip ranges for control plane to `192.168.0.0/28`
- disabling SNAT to ensure full VPC_NATIVE cluster
- enabling control plane global access to allow connectivity from subnets in any region
- adding network tags support to ease IDS inspection
- adding starlark function to simplify network tags enablement
closes #652
> fix: GKE-CLUSTER-AUTOPILOT changing subnet and adding ids network tag

- solutions/core-landing-zone/lz-folder/audits/logging-project/project-iam.yaml
Closes #660
Modify data access log configuration on the logging project in the core-landing-zone project, as per recommendation. This will help reduce logging costs.
Remove ADMIN_READ and DATA_WRITE from the config, leaving on DATA_READ
```yaml
auditLogConfigs:
- logType: DATA_READ
```
> fix: modify logging project data access config

- solutions/ids/README.md
- solutions/ids/endpoint/endpoint.yaml
- solutions/ids/endpoint/mirroring.yaml
- solutions/ids/endpoint/setters.yaml
- solutions/ids/firewall.yaml
- solutions/ids/peering.yaml
- solutions/ids/securitycontrols.md
- solutions/ids/services.yaml
- solutions/ids/setters.yaml
- improving documentation and security controls
- adding a firewall rule to ensure egress traffic towards private service access is allowed.
**_ADDITIONAL CONTEXT_**: when you deploy an IDS endpoint, a forwarding rule is created within the IP range assigned for private service access. To ensure IDS works, all GCE and GKE have to be able to send traffic to this ip. Traffic is replicated to this ip because of the packet mirroring policy that is attached to all resources specified by the filter.
closes #617
> fix: IDS, adding firewall rule to PSA and documentation

- solutions/experimentation/client-project/network/nat.yaml
Closes #670
Enable logging on ComputeRouterNAT resources in experimentation client-project package.
Enables logging for Cloud NAT
https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computerouternat
**Spec:**
```yaml
logConfig:
enable: boolean
filter: string
```
Spec to implement (ALL=Translation and errors):
```yaml
logConfig:
enable: true
filter: ALL
```
> feat: enable logging on ComputeRouterNAT resources in experimentation client-project

- solutions/experimentation/core-landing-zone/mgmt-project/project-sink.yaml
Closes #672
Remove disabling the _default bucket sink in the mgmt project in experimentation core-landing-zone package.
> Note
A patch command may be required to reconcile the root sync as removing this resource will attempt to delete the entire sink.
Once the resource is patched, the sink will need to be re-enabled using the Console or the gcloud cli:
*Replace `management-project-id` with your management project id
```shell
gcloud logging sinks update _Default --no-disabled --project=management-project-id
```
```shell
RESOURCE=logginglogsink.logging.cnrm.cloud.google.com/mgmt-project-cluster-disable-default-bucket
NAMESPACE=logging
kubectl patch $RESOURCE -n $NAMESPACE \
--type json \
--patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
```
> feat: remove disabling the _default bucket sink in the mgmt project

- solutions/client-setup/namespaces/client-name-logging.yaml
- solutions/core-landing-zone/namespaces/logging.yaml
- solutions/experimentation/core-landing-zone/namespaces/logging.yaml
- solutions/legacy/landing-zone-v2/namespaces/logging.yaml
Closes #682
Remove BigQuery IAM permissions since they are not required.
- client-setup
- core-landing-zone
- experimentation/core-landing-zone
- legacy/landing-zone-v2
> feat: remove unused bigquery iam permissions

- solutions/client-landing-zone/client-folder/folder-sink.yaml
- solutions/core-landing-zone/lz-folder/services-infrastructure/folder-sink.yaml
- solutions/core-landing-zone/lz-folder/services/folder-sink.yaml
- solutions/core-landing-zone/mgmt-project/project-sink.yaml
- solutions/core-landing-zone/org/org-sink.yaml
- solutions/experimentation/client-landing-zone/client-folder/folder-sink.yaml
- solutions/experimentation/core-landing-zone/lz-folder/tests/folder-sink.yaml
- solutions/experimentation/core-landing-zone/mgmt-project/project-sink.yaml
- solutions/experimentation/core-landing-zone/org/org-sink.yaml
closes #687
- explicitly set `spec.disabled` to false for `kind: LoggingLogSink`
> fix: specify log sinks spec.disabled field value to false

- solutions/core-landing-zone/lz-folder/audits/logging-project/project-sink.yaml
- solutions/core-landing-zone/org/org-sink.yaml
Closes #685
Remove data access filtering on the org sink as per recommendation. This will prevent routing all data access logs to the security bucket. We will only route data access logs from the logging project (DATA_READ) into the security log bucket.
Remove data access from the current org sink
create a new sink strictly for data access logs, including the spec includeChildren: false
create sink on the logging project to route data access logs to the security log bucket.
Modify security control documentation.
> feat: remove data access from org sink

- .github/dependabot.yaml
- .github/workflows/release-please.yaml
Addressing a few more security issues the previous PR did not. Added dependabot to address [#2](https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/security/code-scanning/2) and adjusted permission on release-please to be write at the job level but read-only at the global level [#28](https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/security/code-scanning/28)
> fix: added dependabot file and adjusted permissions in release-please

- .github/workflows/release-please.yaml
Adjusts release please permissions to be under `release-please` block in the github actions definition instead of under `jobs`.
> fix: adjusted release-please permissions to be under job name

- solutions/experimentation/core-landing-zone/README.md
- solutions/experimentation/core-landing-zone/lz-folder/audits/logging-project/project-sink.yaml
- solutions/experimentation/core-landing-zone/org/org-sink.yaml
- solutions/experimentation/core-landing-zone/setters.yaml
Closes #701
Remove data access filtering on the org sink as per recommendation. This will prevent routing all data access logs to the security bucket. We will only route data access logs from the logging project (DATA_READ) into the security log bucket.
Remove data access from the current org sink
create a new sink strictly for data access logs, including the spec includeChildren: false
create sink on the logging project to route data access logs to the security log bucket.
Modify security control documentation.
> feat: modify data access filtering from org sink and add new sinks in experimentation

- solutions/core-landing-zone/README.md
- solutions/core-landing-zone/lz-folder/audits/logging-project/cloud-logging-buckets.yaml
- solutions/core-landing-zone/lz-folder/audits/logging-project/project-sink.yaml
- solutions/core-landing-zone/org/org-sink.yaml
- solutions/core-landing-zone/setters.yaml
Closes #706 
As per the discussion with CaC folks, we will rename our security log sink and data access sink as follows to be compliant:
org-log-sink-security-{logging-project-id}
org-log-sink-data-access-{logging-project-id}
For the security log bucket, we will hardcode the value to `security-log-bucket` and remove the value from the setters, as this resource is not required to be globally unique.
> fix: rename org sinks add security log bucket

- solutions/experimentation/core-landing-zone/README.md
- solutions/experimentation/core-landing-zone/lz-folder/audits/logging-project/project-sink.yaml
- solutions/experimentation/core-landing-zone/org/org-sink.yaml
- solutions/experimentation/core-landing-zone/setters.yaml
Closes #708
As discussed with CaC folks, we will rename our security log sink and data access sink to comply.
Changes for experimentation/core-landing-zone package:
org-log-sink-security-{logging-project-id}
org-log-sink-data-access-{logging-project-id}
For the security log bucket, we will hardcode the value to `security-log-bucket` and remove the value from the setters, as this resource is not required to be globally unique.
> fix: rename org sinks and security log bucket

- solutions/core-landing-zone/README.md
- solutions/core-landing-zone/lz-folder/audits/logging-project/project-iam.yaml
- solutions/experimentation/core-landing-zone/README.md
- solutions/experimentation/core-landing-zone/lz-folder/audits/logging-project/project-iam.yaml
Closes #715
Refer to #707
Update stale security log refs in the following packages:
- solutions/core-landing-zone/lz-folder/audits/logging-project/project-iam.yaml
- solutions/experimentation/core-landing-zone/lz-folder/audits/logging-project/project-iam.yaml
From:
`logging-project-id-security-sink # kpt-set: ${logging-project-id}-security-sink`
To:
`org-log-sink-security-logging-project-id # kpt-set: org-log-sink-security-${logging-project-id}`
> fix: update stale org sink refs

- examples/landing-zone-v2/configconnector/tier3/cloud-armor/security-policy.yaml
update cloud armor policy to use v33 of preconfigured waf rules. All lists are using distinct rules.
- lfi-v33-stable
- rfi-v33-stable
- rce-v33-stable
- methodenforcement-v33-stable
- scannerdetection-v33-stable
- protocolattack-v33-stable
- sessionfixation-v33-stable
- xss-v33-stable
The list below are not included in this example as they are more application specific and will be evaluated on a per application basis
- nodejs-v33-stable
- java-v33-stable
- php-v33-stable
- sqli-v33-stable
- cve-canary(Apache Log4j CVE-2021-44228)
- json-sqli-canary(JSON-formatted content SQLi)
credit to Yan Bellerose for this repository https://github.com/ybellerose/GCP-Cloud-Armor/tree/main
closes #730
> feat: cloud armor - upgrade preconfigured waf list to v33

- solutions/core-landing-zone/org/org-sink.yaml
core-landing-zone update for logging solution
adding `sensitiveaction.googleapis.com/action` to `org-log-sink-security-logging-project-id`
https://cloud.google.com/security-command-center/docs/how-to-use-sensitive-actions#example_finding_formats
closes #733
> feat: logging - adding sensitive actions

- docs/landing-zone-v2/README.md
Test results on https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/743
- via https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/docs/landing-zone-v2#gitops "If you have forgotten the name of the instance you can run gcloud config controller list to reveal the instances in your project." to
"If you have forgotten the name of the instance you can run gcloud anthos config controller list to reveal the instances in your project."
```
admin_@cloudshell:~/pdt-arg (pdt-arg-kcc11)$ gcloud config controller list
ERROR: (gcloud.config) Invalid choice: 'controller'.
Maybe you meant:
gcloud anthos
gcloud config
```
- same as https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/blob/gh446-hub/solutions/setup.sh#L203
``` …
```
> fix config controller list - documentation #743

- solutions/gke/configconnector/gke-setup/README.md
- solutions/gke/configconnector/gke-setup/project-iam.yaml
Closes #762
As previously discussed, the choice of enabling data access logs falls onto the client. Therefore, we will be removing the data access configuration from the `gke-setup` package.
> fix: removing data access config from gke-setup

- solutions/experimentation/core-landing-zone/README.md
- solutions/experimentation/core-landing-zone/namespaces/logging.yaml
Closes #775
Adding the storage admin role `roles/storage.admin` to the logging service account in experimentation/core-landing-zone.
> fix: adding storage admin role to logging sa

- solutions/experimentation/core-landing-zone/README.md
- solutions/experimentation/core-landing-zone/lz-folder/audits/logging-project/cloud-storage-buckets.yaml
- solutions/experimentation/core-landing-zone/setters.yaml
Closes #780 
Add missing security-incident-log-bucket to the experimentation core-landing-zone solution.
Permissions for bucket added via previous issue #775.
> feat: add missing storage bucket

- .github/workflows/validate-solutions.yaml
closes #792
add `fetch-depth: 0` to validate-solutions checkout action
> fix: validate-solutions fetch depth

- solutions/experimentation/admin-folder/setters.yaml
- solutions/experimentation/client-landing-zone/setters.yaml
- solutions/experimentation/client-project/setters.yaml
- solutions/experimentation/core-landing-zone/setters.yaml
closes #783 fixed setters.yaml formatting and added comments.
> fix: updating setters formatting and comments

- solutions/project/hub-env/org-policies/exceptions/compute-restrict-cloud-nat-usage-except-hub-project.yaml
see extended live testing on a deployed hub for #766 under #837
gcp
gke object
> Add constraints/compute.restrictCloudNATUsage policy override for hub-env fortigate project - to allow NAT to deploy #837

- solutions/client-setup/README.md
- solutions/client-setup/folder.yaml
- solutions/client-setup/setters.yaml
Closes #887
Adding new setters for client folder display name
> feat: adding new setters for client folder display name

- examples/landing-zone-v2/configconnector/tier3/dns/dns.yaml
- examples/landing-zone-v2/configconnector/tier3/firewall-policy-rules/allow-egress-fqdns.yaml
in preparation for feature #883
update for examples
- **`dns`**:
- update setter to use dns-project-id instead of host-project-id
- **`firewall-policy-rules`**:
- edit spec.firewallPolicyRef to reference the policy on the "classification" folder
> feat: distinct VPC host prep examples

- solutions/core-landing-zone/README.md
- solutions/core-landing-zone/lz-folder/services-infrastructure/dns-project/dns.yaml
- solutions/core-landing-zone/lz-folder/services-infrastructure/dns-project/project.yaml
- solutions/core-landing-zone/lz-folder/services-infrastructure/dns-project/services.yaml
- solutions/core-landing-zone/securitycontrols.md
- solutions/core-landing-zone/setters.yaml
in preparation for feature #883
**NOTICE**: setters have been modified
- rename the `dns-project-id` setter to `core-dns-project-id` to avoid confusion with the upcoming new dns project in the client-landing-zone
> feat: distinct VPC host prep core-landing-zone

- solutions/gke/configconnector/gke-defaults/README.md
- solutions/gke/configconnector/gke-defaults/gateway-setup/dns/setters.yaml
- solutions/gke/configconnector/gke-defaults/setters.yaml
in preparation for feature #883
**NOTICE**: setters have been modified
**`gke-defaults`** package:
- update setter instructions for dns-project-id
- cleanup the host-project-id setter which was not used
> feat: distinct VPC host prep gke-defaults

- solutions/gke/configconnector/gke-cluster-autopilot/README.md
- solutions/gke/configconnector/gke-cluster-autopilot/app-infra-classification-folder/firewall.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/gke.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/host-project/firewall.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/host-project/subnet.yaml
- solutions/gke/configconnector/gke-cluster-autopilot/securitycontrols.md
- solutions/gke/configconnector/gke-cluster-autopilot/setters.yaml
**BREAKING CHANGE**
the firewall policies in this package will only work with the latest "distinct host project" design
in preparation for feature #883
**NOTICE**: setters have been modified
**`gke-cluster-autopilot`** package:
- firewall policy rules in `application-infrastructure-folder/`: folder renamed and resources updated to reference (spec.firewallPolicyRef) the proper "classification" policy.
- refactor setters with a similar approach to client-project-setup, to be able to update references based on classification
- standardize how `networkRef` reference a network
> feat: distinct VPC host prep gke-cluster-autopilot BREAKING CHANGE

- solutions/experimentation/core-landing-zone/Kptfile
- solutions/experimentation/core-landing-zone/namespaces/projects.yaml
- solutions/experimentation/core-landing-zone/set-labels-project.yaml
> feat: add cbrid to experimentation core landing zone

- solutions/client-setup/README.md
- solutions/client-setup/namespaces/client-name-networking.yaml
- solutions/client-setup/securitycontrols.md
- solutions/client-setup/setters.yaml
supports #883 
- rename setter `dns-project-id` to `core-dns-project-id` for consistency
- rename the permission name using that setter to include the id to minimize immutable field errors when values change
> fix: update core dns project setter name
