GoogleCloudPlatform/pubsec-declarative-toolkit

solutions/landing-zone/cicd-examples/.gitlab-ci.yml, solutions/landing-zone/cicd-examples/README.md, solutions/landing-zone/cicd-examples/cloudbuild.yaml
Added CICD Examples Folder with files for Gitlab and Cloud Build to start.
=> added cicd examples in LZ solution

solutions/guardrails/README.md, solutions/landing-zone/README.md
Added manual step for setting the default logging storage location. This helps to ensure only target regions are used for logging storage (ie region located in Canada).
=> added manual step for setting logging storage default location

solutions/landing-zone/README.md
Thanks Chris for the id/number link https://cloud.google.com/resource-manager/docs/creating-managing-projects#gcloud_1
Running as part of #99
=> #98 - detail project number retrieval

solutions/guardrails/README.md
Full regression testing
```
Welcome to Cloud Shell! Type "help" to get started.
To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
michael@cloudshell:~$ history
1  history
2  ls
3  history
4  ls
5  history
michael@cloudshell:~$ gcloud config set project pubsec-declarative-tk-apgz
Updated property [core/project].
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ export REGION=northamerica-northeast1
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ export PROJECT_ID=$(gcloud config list --format 'value(core.project)')
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ export ORG_ID=$(gcloud projects get-ancestors $PROJECT_ID --format='get(id)' | tail -1)
michael@cloudshell:~ (pubsec-declarative-tk-apgz)$ echo $ORG_ID
431498985862 …
```
=> #104 - gcloud fix - add pull/105 later in regr tst

solutions/landing-zone/README.md
Added missing `delete` command to clean-up example.
=> updated missing delete command

solutions/landing-zone/environments/nonprod/firewall/firewall.yaml
=> fixed nonprod firewall

cli/internal/cmdcreate/cmdcreate.go
Adjusted the caching mechanism for creating Config Controller clusters. The cache will not track the creation process by cluster name so if a user is creating multiple clusters or re-creating one then as long as the name of the cluster is unique the process tracking cache file `.create` doesn't need to be deleted.
=> FIXED: create command not tracking multiple config controller creates

solutions/landing-zone-namespaced/landing-zone/Kptfile, solutions/landing-zone-namespaced/landing-zone/hierarchy.yaml, solutions/landing-zone-namespaced/landing-zone/setters.yaml
=> resolve #184 : adding multi-tenant folder/hierarchy to landing zone namespaced

docs/advanced-install.md, solutions/landing-zone/README.md, solutions/landing-zone/setters.yaml
Draft over the weekend 
Testing each change as part of a clean org deploy
Sections in readme s are required to be able to link into/from code
kcc cluster can be autopilot - added flag - thanks Chris
section on CSR apply added
adjustments to setters.yaml for proj adjustments
=> #191 - #195 - add CSR k8s apply - add autopilot flag - add bootstrap instructions/script

solutions/landing-zone/deployment.sh, solutions/landing-zone/vars.sh
=> add kpt live apply section and lz deletion

solutions/landing-zone/README.md
Updated some gaps in the LZ Readme docs.
- Added commands to enable cloudbilling and accesscontext management APIs in the management project
- Updated rootsync name and Kubernetes Service Account References
- Renamed landing-zone artifact name.
- Updated missing `${}` around some PROJECT_ID var calls.
=> Updated README Docs

cli/internal/cmdsolution/cmdsolution.go
Fixed the Regular expression to escape the dot in .com
=> Fixed url regex sanitize check

.github/workflows/codeql.yml
Adds vulnerability scanning for code that may be added to the repository.
=> feat: Create codeql.yml

solutions/kcc-namespaces/README.md
word substitution in the  readme, swapped "great" for "create" 
... great is relative :D
=> minor fix(wrong word) to documentation

solutions/logging/core-experimentation/org-sink.yaml
Closes #319 
- updates org-sink's external bucket reference
=> fix: update org-sink bucket reference

solutions/core-landing-zone/Kptfile, solutions/core-landing-zone/README.md
minor update to include a remark about validating with CCCS cloud based sensors before updating org-policies
=> adding cccs remark

README.md
Add a link to the gcp-tools setup-kcc.sh script for config controller bootstrap
=> #296 - Update README.md with setup-kcc.sh link - ready to review/merge

docs/landing-zone-v2/README.md
as part of a client session during an lz install
=> #296 - update step 2 setters.yaml link

solutions/core-landing-zone/setters.yaml
=> #450 - update setters with DIRECTORY_CUSTOMER_ID instructions

solutions/core-landing-zone/setters.yaml
=> #428 - core-lz setters.yaml project number needs derivation

docs/landing-zone-v2/README.md
gatekeeper optional - just instructions for core-landing-zone
Test results of all script additions in #457
=> #457 - add back kpt deploy instructions for core-landing-zone - ready

solutions/core-landing-zone/README.md, solutions/core-landing-zone/org/custom-roles/tier3-subnetwork-admin.yaml, solutions/core-landing-zone/org/custom-roles/tier4-secretmanager-admin.yaml, solutions/core-landing-zone/securitycontrols.md
fix: 
- adding custom roles for Tier3 Subnetwork Admin and Tier4 Secret Manager Admin
- adding securitycontrols.md
=> fix: core-landing-zone package

solutions/client-setup/README.md, solutions/client-setup/securitycontrols.md
fix: just adding standard securitycontrols.md
=> Fix client-setup package

solutions/client-project-setup/README.md, solutions/client-project-setup/namespaces/project-id-tier3.yaml, solutions/client-project-setup/project.yaml, solutions/client-project-setup/root-sync-git/root-sync-git-tier3.yaml, solutions/client-project-setup/root-sync-git/root-sync-git-tier4.yaml, solutions/client-project-setup/securitycontrols.md, solutions/client-project-setup/services.yaml, solutions/client-project-setup/setters.yaml
- adding specific root-sync for tier3 and tier4
- Grant GCP Project IAM Admin to GCP SA on Client Host Project
- Grant GCP role Compute Security Admin to tier3-sa GCP SA
- enable logging and monitoring API
- add securitycontrols.md
=> fix: client-project-setup package

solutions/gke/configconnector/gke-setup/logging-monitoring/pubsub.yaml
Adding the following to ensure the Cloud Pub/Sub subscription never expires
```yaml
expirationPolicy:
ttl: ""
```
=> feat: config pub/sub sub to never expire.

examples/landing-zone-v2/configconnector/tier3/ssl-policies/Kptfile, examples/landing-zone-v2/configconnector/tier3/ssl-policies/setters.yaml
DO NOT MERGE. I'd like to have a review from @alaincormier-ssc as he has created the initial structure under examples
=> feat: adding Kptfile and setters.yaml to ssl-policies example

solutions/client-landing-zone/client-folder/firewall-policy/policy.yaml, solutions/client-landing-zone/client-folder/standard/applications-infrastructure/firewall-policy/policy.yaml, solutions/client-landing-zone/client-folder/standard/firewall-policy/policy.yaml
closes #515
add placeholder comments to facilitate resource acquisition for firewall policies
=> docs: fw policies acquisition comment

solutions/project/hub-env/setters.yaml, solutions/setup.sh, solutions/vars.sh
see testing and main fix in #573
=> #446 - fix hub-env missing org-id

solutions/setup.sh
see https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/584
=> #446 - add separate proj / cluster create/delete

docs/landing-zone-v2/README.md
test results of the script in #570 
ongoing clean org test results in automation in #446
=> #570 - project iam admin instead of project admin

solutions/project/hub-env/project.yaml, solutions/project/hub-env/setters.yaml, solutions/setup.sh, solutions/vars.sh
see #599 for main fix later when time permits
=> #446 - fix 599 missing management-namespace setters.yaml var

solutions/project/hub-env/setters.yaml
see testing in #573
as part of #446
=> #573 - hub-env setters.yaml missing org-id

solutions/gke/configconnector/gke-defaults/gateway-setup/ssl-certificate/README.md, solutions/gke/configconnector/gke-defaults/gateway-setup/ssl-certificate/setters.yaml, solutions/gke/configconnector/gke-defaults/gateway-setup/ssl-certificate/ssl.yaml
=> fix: ssl cert alpha changes

solutions/client-project-setup/services.yaml, solutions/client-setup/mgmt-project/services.yaml, solutions/experimentation/client-project/services.yaml, solutions/experimentation/core-landing-zone/mgmt-project/services.yaml, solutions/gke/configconnector/gke-setup/services.yaml, solutions/project/hub-env/services.yaml, solutions/project/project-experimentation/services.yaml, solutions/project/spoke-unclass-env/services.yaml, solutions/vertexai/ai-experimentation/services.yaml
Second round of commits that addresses issue #677
=> fix: updated services objects to use projectRef instead of annotations

examples/landing-zone-v2/configconnector/tier3/client-project-iam/Kptfile, examples/landing-zone-v2/configconnector/tier3/client-project-iam/README.md, examples/landing-zone-v2/configconnector/tier3/client-project-iam/iam-tier4-sa.yaml, examples/landing-zone-v2/configconnector/tier3/client-project-iam/iam-users.yaml, examples/landing-zone-v2/configconnector/tier3/client-project-iam/setters.yaml
closes #723
add example to manage client project permissions from tier3
=> feat: add example to manage client project iam permissions

examples/landing-zone-v2/configconnector/tier3/client-project-iam/iam-tier4-sa.yaml, examples/landing-zone-v2/configconnector/tier3/client-project-iam/iam-users.yaml
=> modifying security controls for client project iam package

docs/landing-zone-v2/README.md
see testing in #766
details in #802
=> #802 - kpt live apply reconcile-timeout from 2 to 15 min

solutions/gke/configconnector/gke-cluster-autopilot/README.md, solutions/gke/configconnector/gke-cluster-autopilot/gke.yaml, solutions/gke/configconnector/gke-cluster-autopilot/setters.yaml
=> feat: enable group for rbac gke

.github/workflows/linter.yaml
linter will not pass
source ./vars.sh
=> #862 - remove cli - add gcloud to linter exclusion

.github/CODEOWNERS
We can add anyone else from the team to these sections of the code in the CODEOWNERS list as well
=> #860 - Update CODEOWNERS

solutions/client-setup/Kptfile, solutions/client-setup/set-labels-project.yaml, solutions/client-setup/setters.yaml
=> feat: adding cbrid to client setup package

solutions/experimentation/client-project/Kptfile, solutions/experimentation/client-project/set-labels-project.yaml
=> feat: add cbrid to client project

solutions/client-setup/setters.yaml
the previous commit did not generate a new version of the client-setup package. This PR is to generate that new version
=> fix: adding client folder display name

solutions/gke/configconnector/gke-cluster-autopilot/gkehub-featuremembership-acm.yaml, solutions/gke/configconnector/gke-cluster-autopilot/setters.yaml, solutions/gke/kubernetes/namespace-defaults/cd/gitops-config-sync.yaml, solutions/gke/kubernetes/namespace-defaults/setters.yaml
- changed  \<x-fleet-id\> and \<namespace\> to as they were causing render issues in git gui
- templates already updated
=> fix:  changed <x-fleet-id> and <namespace> to as they were causing render issues in git gui

docs/landing-zone-v2/README.md
=> #912 - fix anthos delete
